// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2619.SirLancebot2016;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainLeftFrontMotor;
    public static WPI_TalonSRX driveTrainLeftRearMotor;
    public static WPI_TalonSRX driveTrainRightFrontMotor;
    public static WPI_TalonSRX driveTrainRightRearMotor;
    public static DoubleSolenoid gearShiftshifter;
    public static Solenoid plungerbopper;
    public static Solenoid wrist;
    public static WPI_TalonSRX shooterleftShooterMotor;
    public static WPI_TalonSRX shooterrightShooterMotor;
    public static DoubleSolenoid shootershooterLift;
    public static DoubleSolenoid collectorarmLift;
    public static WPI_TalonSRX collectorfeedRoller;
    public static WPI_TalonSRX collectorcenterRoller;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static final int TIMEOUT_MS = 100;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftFrontMotor = new WPI_TalonSRX(11);
        LiveWindow.addActuator("DriveTrain", "leftFrontMotor", driveTrainLeftFrontMotor);
        
        driveTrainLeftRearMotor = new WPI_TalonSRX(10);
        LiveWindow.addActuator("DriveTrain", "leftRearMotor", driveTrainLeftRearMotor);
        
        driveTrainRightFrontMotor = new WPI_TalonSRX(2);
        LiveWindow.addActuator("DriveTrain", "rightFrontMotor", driveTrainRightFrontMotor);
        
        driveTrainRightRearMotor = new WPI_TalonSRX(3);
        LiveWindow.addActuator("DriveTrain", "rightRearMotor", driveTrainRightRearMotor);
        
        gearShiftshifter = new DoubleSolenoid(0, 6,7);
        LiveWindow.addActuator("GearShift", "shifter", gearShiftshifter);
        
        plungerbopper = new Solenoid(4);
        LiveWindow.addActuator("Plunger", "bopper", plungerbopper);
        
        wrist = new Solenoid(5);
        LiveWindow.addActuator("Wrist", "wrist", wrist);
        
        shooterleftShooterMotor = new WPI_TalonSRX(9);
        LiveWindow.addActuator("Shooter", "leftShooterMotor", shooterleftShooterMotor);
        
        shooterrightShooterMotor = new WPI_TalonSRX(4);
        LiveWindow.addActuator("Shooter", "rightShooterMotor", shooterrightShooterMotor);
        
        shootershooterLift = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("Shooter", "shooterLift", shootershooterLift);
        
        collectorarmLift = new DoubleSolenoid(0, 2, 3);
        LiveWindow.addActuator("Collector", "armLift", collectorarmLift);
        
        collectorfeedRoller = new WPI_TalonSRX(8);
        LiveWindow.addActuator("Collector", "feedRoller", collectorfeedRoller);
        
        collectorcenterRoller = new WPI_TalonSRX(5);
        LiveWindow.addActuator("Collector", "centerRoller", collectorcenterRoller);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        
        driveTrainLeftFrontMotor.set(0);
        driveTrainLeftRearMotor.set(0);
        
        driveTrainRightFrontMotor.set(0);
        driveTrainRightRearMotor.set(0);
        
        
        // setting all the other motors to follower mode to follow the front two motors
        // Right
        driveTrainRightRearMotor.set(ControlMode.Follower, driveTrainRightFrontMotor.getDeviceID());
        //driveTrainRightRearMotor.set(driveTrainRightFrontMotor.getDeviceID());
        
        // Left
        driveTrainLeftRearMotor.set(ControlMode.Follower, driveTrainLeftFrontMotor.getDeviceID());
        //driveTrainLeftRearMotor.set(driveTrainLeftFrontMotor.getDeviceID());
        
        //Invert motors
        //THESE ARE FOR PLYBOT
        driveTrainRightFrontMotor.setInverted(true);
        driveTrainRightRearMotor.setInverted(true);

    }
}
