// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2619.SirLancebot2016.subsystems;

import org.usfirst.frc2619.TheChargeDashboard;
import org.usfirst.frc2619.SirLancebot2016.Robot;
import org.usfirst.frc2619.SirLancebot2016.RobotMap;
import org.usfirst.frc2619.SirLancebot2016.commands.*;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.DoubleSolenoid;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Shooter extends Subsystem {

	private final static double SPEED_P_CONSTANT = .75;
    private final static double SPEED_I_CONSTANT = .01;
    private final static double SPEED_D_CONSTANT = 0;
    private final static double SPEED_F_CONSTANT = 1;
    public double speed = .8;
    
    double SpeedP = SPEED_P_CONSTANT;
    double SpeedI = SPEED_I_CONSTANT;
    double SpeedD = SPEED_D_CONSTANT;
    double SpeedF = SPEED_F_CONSTANT;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX leftShooterMotor = RobotMap.shooterleftShooterMotor;
    private final WPI_TalonSRX rightShooterMotor = RobotMap.shooterrightShooterMotor;
    private final DoubleSolenoid shooterLift = RobotMap.shootershooterLift;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public Shooter()
    {
    	writeDefaultDashboardValues();
    	initSpeedMode();
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    private void writeDefaultDashboardValues() {
    	TheChargeDashboard.putNumber("ShooterSpeedP", SPEED_P_CONSTANT);
    	TheChargeDashboard.putNumber("ShooterSpeedI", SPEED_I_CONSTANT);
    	TheChargeDashboard.putNumber("ShooterSpeedD", SPEED_D_CONSTANT);
    	TheChargeDashboard.putNumber("ShooterSpeedF", SPEED_F_CONSTANT);
    	TheChargeDashboard.putNumber("ShooterSpeedFromPot", speed);
	}
    
    public void readDashboardControlValues()
    {
    	SpeedP = SmartDashboard.getNumber("ShooterSpeedP", SPEED_P_CONSTANT);
    	SpeedI = SmartDashboard.getNumber("ShooterSpeedI", SPEED_I_CONSTANT);
    	SpeedD = SmartDashboard.getNumber("ShooterSpeedD", SPEED_D_CONSTANT);
    	SpeedF = SmartDashboard.getNumber("ShooterSpeedF", SPEED_F_CONSTANT);
    	
    	//set CANTalon PIDs
    	//leftShooterMotor.setPID(SpeedP, SpeedI,SpeedD, SpeedF, 0, 0, 0);
    	//rightShooterMotor.setPID(SpeedP, SpeedI, SpeedD, SpeedF, 0, 0, 0);
    	
    	leftShooterMotor.config_kP(1, SpeedP, RobotMap.TIMEOUT_MS);
    	leftShooterMotor.config_kI(1, SpeedI, RobotMap.TIMEOUT_MS);
    	leftShooterMotor.config_kD(1, SpeedD, RobotMap.TIMEOUT_MS);
    	leftShooterMotor.config_kF(1, SpeedF, RobotMap.TIMEOUT_MS);

    	rightShooterMotor.config_kP(1, SpeedP, RobotMap.TIMEOUT_MS);
    	rightShooterMotor.config_kI(1, SpeedI, RobotMap.TIMEOUT_MS);
    	rightShooterMotor.config_kD(1, SpeedD, RobotMap.TIMEOUT_MS);
    	rightShooterMotor.config_kF(1, SpeedF, RobotMap.TIMEOUT_MS);
    }
    
    public void writeDashboardDebugValues()
	{
		//Output Speed of Encoders
		//TheChargeDashboard.putNumber("ShooterLeftSpeed",leftShooterMotor.getEncVelocity());
		//TheChargeDashboard.putNumber("ShooterRightSpeed",rightShooterMotor.getEncVelocity());
	}
    
    public void initSpeedMode()
    {
    	leftShooterMotor.set(ControlMode.Velocity, 0);
    	rightShooterMotor.set(ControlMode.Velocity, 0);
    }
    /**
     * 
     * @param speed double percent of speed to run at 
     */
    public void prepShooter(double speed) // TODO: add constant (like MAX_TICKS_PER_SECOND)
    {
    	leftShooterMotor.set(-speed);
    	rightShooterMotor.set(speed);
    }
    
    public void intake(double speed)  //needed to get speed from somewhere else???
    {
    	leftShooterMotor.set(speed);
    	rightShooterMotor.set(-speed);   
	}
    
    public void liftShooter()
    {
    	shooterLift.set(DoubleSolenoid.Value.kForward);
    }
    
    public void lowerShooter()
    {
    	shooterLift.set(DoubleSolenoid.Value.kReverse);
    }
    
    public void stop()
    {
    	leftShooterMotor.set(0);
    	rightShooterMotor.set(0);
    }
    
}

